# Generated by Django 5.2.5 on 2025-08-17 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('cnic', models.CharField(blank=True, max_length=13, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('townId', models.IntegerField()),
                ('fileNo', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
