# Generated by Django 5.2.5 on 2025-08-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='buyer',
            name='townId',
        ),
        migrations.AddField(
            model_name='buyer',
            name='town',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
