# Generated by Django 5.2.5 on 2025-08-18 08:36

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dealer', '0002_commission'),
    ]

    operations = [
        migrations.CreateModel(
            name='DealerLedger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('Commission', 'Commission'), ('Payout', 'Payout'), ('Adjustment', 'Adjustment')], max_length=20)),
                ('description', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('dealer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ledger', to='dealer.dealer')),
            ],
        ),
    ]
