# Generated by Django 5.2.5 on 2025-08-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('offices', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('townName', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('totalPlots', models.IntegerField()),
                ('mapUrl', models.URLField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('offices', models.ManyToManyField(blank=True, related_name='towns', to='offices.office')),
            ],
        ),
    ]
